apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-bff
  namespace: bookstore-ns
  labels:
    app: mobile-bff
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mobile-bff
  template:
    metadata:
      labels:
        app: mobile-bff
    spec:
      containers:
        - name: mobile-bff
          image: REPLACE_ME/mobile-bff:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: URL_BASE_BACKEND_SERVICES
              value: "http://internal-gateway.bookstore-ns.svc.cluster.local:3000"
          livenessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
