apiVersion: v1
kind: Service
metadata:
  name: mobile-bff
  namespace: bookstore-ns
  labels:
    app: mobile-bff
spec:
  type: LoadBalancer
  selector:
    app: mobile-bff
  ports:
    - name: http
      port: 80
      targetPort: http
